#!/bin/bash

#Black        0;30     Dark Gray     1;30
#Red          0;31     Light Red     1;31
#Green        0;32     Light Green   1;32
#Brown/Orange 0;33     Yellow        1;33
#Blue         0;34     Light Blue    1;34
#Purple       0;35     Light Purple  1;35
#Cyan         0;36     Light Cyan    1;36
#Light Gray   0;37     White         1;37

COLOR1='\033[1;35m'
COLOR2='\033[1;37m'
COLOR3='\033[0;32m'

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONKYRC="${CURR_DIR}/conkyrc"
TMP_FILE="${CURR_DIR}/tmp"


conky  -q -c $CONKYRC > $TMP_FILE -i 1

while IFS= read -r LINE
do
  LABEL=$(echo $LINE | cut -d ":" -f 1)
  VALUES=$(echo $LINE | cut -d ":" -f 2)
  echo -e "${COLOR3}[+] ${COLOR1}$LABEL":${COLOR2}"$VALUES"
done < "$TMP_FILE" 	




